// post에 대한 액션
export const POST_CREATE = "POST_CREATE";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAILURE = "POST_CREATE_FAILURE";

export const POST_READ = "POST_READ";
export const POST_READ_SUCCESS = "POST_READ_SUCCESS";
export const POST_READ_FAILURE = "POST_READ_FAILURE";

export const POST_UPDATE = "POST_UPDATE";
export const POST_UPDATE_SUCCESS = "POST_UPDATE_SUCCESS";
export const POST_UPDATE_FAILURE = "POST_UPDATE_FAILURE";

export const POST_DELETE = "POST_DELETE";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_FAILURE = "POST_DELETE_FAILURE";